
#define SetMiddleColor MkStr(SetMiddleColor)
#define SetMiddleColorWithTable MkStr(SetMiddleColorWithTable)
#define CreateColor MkStr(CreateColor)
#define Copy1Pixel MkStr(Copy1Pixel)

#define ClearRect_Xbpp	MkStrB(ClearRect_)
#define FadeRect_Xbpp	MkStrB(FadeRect_)
#define CopyAllWithMask_Xbpp	MkStrB(CopyAllWithMask_)
#define CopyRectWithoutColor_Xbpp	MkStrB(CopyRectWithoutColor_)
#define CopyRectWithMask_Xbpp	MkStrB(CopyRectWithMask_)
#define CopyRectWithFade_Xbpp	MkStrB(CopyRectWithFade_)
#define ConvertMonochrome_Xbpp	MkStrB(ConvertMonochrome_)
#define InvertColor_Xbpp	MkStrB(InvertColor_)
#define CopyRectWithStretch_Xbpp	MkStrB(CopyRectWithStretch_)
#define CopyRectWithTransform_Xbpp	MkStrB(CopyRectWithTransform_)
#define CopyRectWithFadeWithStretch_Xbpp	MkStrB(CopyRectWithFadeWithStretch_)
#define CopyRectWithFadeWithMask_Xbpp	MkStrB(CopyRectWithFadeWithMask_)
#define CopyWithSel_Xbpp		MkStrB(CopyWithSel_)
#define CopyWithSelWithMask_Xbpp	MkStrB(CopyWithSelWithMask_)
#define DrawChara_Xbpp		MkStrB(DrawChara_)
#define SetMojiBit_fadepixel	MkStrB(SetMojiBit_fadepixel)
#define SetMojiBit_clearpixel	MkStrB(SetMojiBit_clearpixel)
#define SetMojiBit_nothing	MkStrB(SetMojiBit_nothing)
